boonai/project/site/routes.py
from flask import Blueprint, render_template
from flask_user import login_required, roles_required

mod = Blueprint('site', __name__, template_folder='templates')

# TODO: Needs to be split in multiple files - blueprints already in place so it's simple


def _get_link(links, rel_value):
    for l in links:
        if l['rel'] == rel_value:
            return l['href']
    raise ValueError('No file relation found in the links list')


@mod.route('/')
def root():
    return render_template('site/index.html')


# The Members page is only accessible to authenticated users
@mod.route('/members')
@login_required  # Use of @login_required decorator
def member():
    print('Member.')
    return render_template('site/index.html')


# The Admin page requires an 'Admin' role.
@mod.route('/admin')
@roles_required('Admin')  # Use of @roles_required decorator
def admin():
    print('Admin!')
    return render_template('site/index.html')


@mod.route('/labeling', methods=['GET', 'POST'])
@login_required
def labeling():
    return "<h1>Fake page</h1>"

boonai/project/templates/_formhelpers.html
{% macro render_field(field) %}
  <dt>{{ field.label }}
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}

boonai/project/templates/layout.html
<!doctype html>

<html>
<head>
    <title>BoonAI{% block title %}{% endblock %}</title>

    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">

    <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/style.css') }}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>

    <!-- Bootstrap -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <!--<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>-->
    <!-- Bootstrap -->
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

    {% block head %}{% endblock %}


    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        .alert {
            padding: 5px;
            background-color: #f44336;
            color: white;
            opacity: 1;
            transition: opacity 0.6s;
            margin-bottom: 5px;
        }
        .alert.success {background-color: #4CAF50;}
        .alert.info {background-color: #2196F3;}
        .alert.warning {background-color: #ff9800;}

        .closebtn {
            margin-left: 15px;
            color: white;
            font-weight: bold;
            float: right;
            font-size: 22px;
            line-height: 20px;
            cursor: pointer;
            transition: 0.3s;
        }

        .closebtn:hover {
            color: black;
        }

        {% block style %}{% endblock %}
    </style>

</head>

<body lang="en">
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
{% for category, message in messages %}
<div class="alert {{ category }}">
    <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
    <strong>{{ category|title }}:</strong> {{ message }}
</div>
{% endfor %}
{% endif %}
{% endwith %}

<header>
    <nav class="navbar" style="background-color: rgb(211, 234, 241)">
        <div class="container-fluid">
            <div class="navbar-header">
            <a class="navbar-brand" href={{ url_for('site.root') }}>BoonAI</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                    <li><a href={{ url_for('site_datasets.root') }}>{%trans%}Datasets{%endtrans%}</a></li>
                    <li><a href={{ url_for('site_machine_learning.root') }}>{%trans%}Train & Run{%endtrans%}</a></li>
                    <li><a href={{ url_for('site.labeling') }}>{%trans%}Labeling/Sampling{%endtrans%}</a></li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Members
                        <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href={{ url_for('site.member') }}>{%trans%}Member{%endtrans%}</a></li>
                            <li><a href={{ url_for('site.admin') }}>{%trans%}Admin{%endtrans%}</a></li>
                            <li><a href={{ url_for('user.logout') }}>{%trans%}Sign out{%endtrans%}</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href={{ url_for('user.register') }}>{%trans%}Register{%endtrans%}</a></li>
                    <li><a href={{ url_for('user.login') }}>{%trans%}Sign in{%endtrans%}</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
</header>


<script>
var close = document.getElementsByClassName("closebtn");
var i;
for (i = 0; i < close.length; i++) {
    close[i].onclick = function(){
        var div = this.parentElement;
        div.style.opacity = "0";
        setTimeout(function(){ div.style.display = "none"; }, 200);
    }
}
</script>

{% block body %}{% endblock %}
</body>
</html>

boonai/project/templates/navigation_bar.html
<ul>
    <li><a href={{ url_for('site.root') }}>{%trans%}Home Page{%endtrans%}</a></li>
    <li><a href={{ url_for('site_datasets.root') }}>{%trans%}Datasets Page{%endtrans%}</a></li>
    <li><a href={{ url_for('site_machine_learning.root') }}>{%trans%}Train & Run Models Page{%endtrans%}</a></li>
    <li><a href={{ url_for('site_dataprep.root') }}>{%trans%}DataPrep{%endtrans%}</a></li>
    <li><a href={{ url_for('site.labeling') }}>{%trans%}Sampling{%endtrans%}</a></li>
    <li><a href={{ url_for('user.logout') }}>{%trans%}Sign out{%endtrans%}</a></li>
</ul>

boonai/project/templates/url_list.html
{# url_list.html #}
<ul>
{% for url, endpoint in links %}
<li><a href="{{ url }}">{{ endpoint }}</a></li>
{% endfor %}
</ul>